segundo_uso_frontend_homepage:
    pattern:  /
    defaults: { _controller: SegundoUsoFrontendBundle:Home:home }

segundo_uso_frontend_ad_create:
    pattern: /anuncio/crear
    defaults: { _controller: SegundoUsoAdBundle:Default:create }

segundo_uso_frontend_ad_edit:
    pattern: /anuncios/editar/{pid}/{token}
    defaults: { _controller: SegundoUsoAdBundle:Default:edit }

segundo_uso_frontend_ad_delete:
    pattern: /anuncios/eliminar/{pid}/{token}
    defaults: { _controller: SegundoUsoAdBundle:Default:delete }

segundo_uso_frontend_ad_delete_confirmation:
    pattern: /anuncios/eliminar/confirmacion
    defaults: { _controller: SegundoUsoAdBundle:Default:deleteConfirmation }

segundo_uso_frontend_ad_waiting_confirmation:
    pattern: /anuncio/por-confirmar
    defaults: { _controller: SegundoUsoAdBundle:Default:waitingConfirmation }

segundo_uso_frontend_ad_confirmation:
    pattern: /anuncio/confirmacion/{pid}
    defaults: { _controller: SegundoUsoAdBundle:Default:confirmation }

segundo_uso_frontend_ad_list:
    pattern: /anuncios
    defaults: { _controller: SegundoUsoAdBundle:Default:index }

segundo_uso_frontend_ad_show:
    pattern: /anuncios/{pid}
    defaults: { _controller: SegundoUsoAdBundle:Default:show }

segundo_uso_frontend_manifiesto:
    pattern: /manifiesto
    defaults: { _controller: SegundoUsoFrontendBundle:Corporate:manifiesto }

segundo_uso_frontend_about:
    pattern: /sobre-segundo-uso
    defaults: { _controller: SegundoUsoFrontendBundle:Corporate:about }

segundo_uso_frontend_contact:
    pattern: /contacto
    defaults: { _controller: SegundoUsoFrontendBundle:Corporate:contact }

segundo_uso_frontend_collaborate:
    pattern: /colaborar
    defaults: { _controller: SegundoUsoFrontendBundle:Corporate:colaborate }