SegundoUso\AdBundle\Entity\Ad:
    type: entity
    table: ads
#    repositoryClass: SegundoUso\AdBundle\Repository\AdRepository
    uniqueConstraints:
        IDX_MAN_ANNOUNCEMENT_PID:
          columns: [ pid ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
        description:
            type: text
        location:
            type: string
        pid:
            type: string
            lenght: 64
        token:
            type: string
            lenght: 16
        published:
            type: boolean
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                  on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
                timestampable:
                  on: update
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: ads
            joinColumn:
                name: category_id
                referencedColumnName: id
                nullable: false
            cascade: ['persist']
        advertiser:
            targetEntity: Advertiser
            inversedBy: ads
            joinColumn:
                name: advertiser_id
                referenceColumnName: id
                nullable: true
            cascade: ['persist']
    lifecycleCallbacks: { }